steps:

- name: gcr.io/cloud-builders/docker
  id: 'Build Docker image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image to Container Registry'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA'

- name: gcr.io/cloud-builders/kubectl
  id: 'Configure Production cluster context'
  args: [ 'version' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=next2019-production'
  - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'

- name: gcr.io/cloud-builders/kubectl
  id: 'Deploy to Production'
  entrypoint: '/bin/sh'
  args:
    - -c
    - >
      kubectl create deployment nginx --image=gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA

images: [ 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA' ]

substitutions:
  _IMAGE: nginx-alpine
