steps:

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA', '.']

- name: gcr.io/cloud-builders/kubectl
  args: [ 'version' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=next2019-production'
  - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Generate Kubernetes manifest'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |-
      DIGEST=$(gcloud container images describe --format 'value(image_summary.digest)' gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA)
      sed "s/DIGEST/$${DIGEST}/g" > deployment.yaml

- name: gcr.io/cloud-builders/kubectl
  entrypoint: '/bin/sh'
  args:
    - -c
    - >
      kubectl apply -f deployment.yaml

images: [ 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA' ]

substitutions:
  _IMAGE: nginx-alpine
