steps:

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:latest', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA', '.']

- name: gcr.io/cloud-builders/kubectl
  args: [ 'version' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=next2019'
  - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'

- name: gcr.io/cloud-builders/kubectl
  entrypoint: '/bin/sh'
  args:
    - -c
    - >
      kubectl create deployment nginx --image=gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA

images: [ 'gcr.io/$PROJECT_ID/$_IMAGE:latest', 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA' ]



substitutions:
    _IMAGE: nginx-alpine
