steps:

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:latest', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:$_TAG', '.']

images: [ 'gcr.io/$PROJECT_ID/$_IMAGE:latest', 'gcr.io/$PROJECT_ID/$_IMAGE:$_TAG' ]

substitutions:
    _IMAGE: nginx-alpine
