steps:

- name: gcr.io/cloud-builders/docker
  id: 'Build Docker image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA', '.']

images: [ 'gcr.io/$PROJECT_ID/$_IMAGE:$SHORT_SHA' ]

substitutions:
    _IMAGE: nginx-alpine-dev
